name: Build Mobile Apps
on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # ESSA PARTE RESOLVE O ERRO DE LICENÇA DO ANDROID
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Cordova
        run: npm install -g cordova

      - name: Build APK
        run: |
          cordova create myApp com.bulymist.myapp MyApp
          cp index.html myApp/www/index.html
          cd myApp
          cordova platform add android@12.0.0
          # Configura Android Antigo e Novo
          sed -i 's/android-minSdkVersion" value="22"/android-minSdkVersion" value="21"/' config.xml
          sed -i 's/android-targetSdkVersion" value="33"/android-targetSdkVersion" value="34"/' config.xml
          cordova build android --debug --device

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-android
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cordova
        run: npm install -g cordova
      - name: Build iOS
        run: |
          cordova create myApp com.bulymist.myapp MyApp
          cp index.html myApp/www/index.html
          cd myApp
          cordova platform add ios
          cordova build ios --emulator --no-sign
      - name: Upload iOS Payload
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-ios
          path: myApp/platforms/ios/build/emulator/
